### ISSUE TITLE
WIP: 1.0 Upgrade to ESM Progress

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/.github#1]
Argument: We need ESM because upstream packages require it, specifically the ones used in `orbit-db-io`. I propose a multi-step process that allows us to use backwards compatible `pkg/cjs` builds so that we can do this incrementally over time rather than all at once.

- [x] `orbit-db-test-utils`
- [x] `orbit-db-io`
- [ ] `ipfs-log`
- [ ] `orbit-db-storage-adapter`
- [ ] `orbit-db-keystore`
- [ ] `orbit-db-cache`
- [ ] `orbit-db-identity-provider`
- [ ] `crdts`
- [ ] `orbit-db-counterstore`
- [ ] `orbit-db-kvstore`
- [ ] `orbit-db-eventstore`
- [ ] `orbit-db-feedstore`
- [ ] `orbit-db-docstore`
- [ ] `orbit-db`

more TBD...

**Comment by haadcode** [comment]
This was done recently.
